# Important Libraries

In [2]:
import pandas as pd

# Load The dataset

In [4]:
df = pd.read_csv('Ball_By_Ball_Match_Data.csv')

In [5]:
# see the first 5 rows of the dataset
df.head()

,ID,Innings,Overs,BallNumber,Batter,Bowler,NonStriker,ExtraType,BatsmanRun,ExtrasRun,TotalRun,IsWicketDelivery,PlayerOut,Kind,FieldersInvolved,BattingTeam
0,501208,1,0,1,S Sohal,Z Khan,S Dhawan,NaN,0,0,0,0,NaN,NaN,NaN,Deccan Chargers
1,501208,1,0,2,S Sohal,Z Khan,S Dhawan,NaN,1,0,1,0,NaN,NaN,NaN,Deccan Chargers
2,501208,1,0,3,S Dhawan,Z Khan,S Sohal,NaN,1,0,1,0,NaN,NaN,NaN,Deccan Chargers
3,501208,1,0,4,S Sohal,Z Khan,S Dhawan,NaN,0,0,0,0,NaN,NaN,NaN,Deccan Chargers
4,501208,1,0,5,S Sohal,Z Khan,S Dhawan,wides,0,1,1,0,NaN,NaN,NaN,Deccan Chargers

In [6]:
# see the last 5 rows of the dataset
df.tail()

,ID,Innings,Overs,BallNumber,Batter,Bowler,NonStriker,ExtraType,BatsmanRun,ExtrasRun,TotalRun,IsWicketDelivery,PlayerOut,Kind,FieldersInvolved,BattingTeam
295727,1359499,2,19,2,Abdul Samad,Arjun Tendulkar,B Kumar,NaN,1,0,1,1,Abdul Samad,run out,"Ishan Kishan,HR Shokeen",Sunrisers Hyderabad
295728,1359499,2,19,3,M Markande,Arjun Tendulkar,B Kumar,wides,0,1,1,0,NaN,NaN,NaN,Sunrisers Hyderabad
295729,1359499,2,19,4,M Markande,Arjun Tendulkar,B Kumar,NaN,2,0,2,0,NaN,NaN,NaN,Sunrisers Hyderabad
295730,1359499,2,19,5,M Markande,Arjun Tendulkar,B Kumar,legbyes,0,1,1,0,NaN,NaN,NaN,Sunrisers Hyderabad
295731,1359499,2,19,6,B Kumar,Arjun Tendulkar,M Markande,NaN,0,0,0,1,B Kumar,caught,RG Sharma,Sunrisers Hyderabad

In [7]:
# Dataset shape 
df.shape

(295732, 16)

In [8]:
# See the columns of the dataset
df.columns

Index(['ID', 'Innings', 'Overs', 'BallNumber', 'Batter', 'Bowler',
       'NonStriker', 'ExtraType', 'BatsmanRun', 'ExtrasRun', 'TotalRun',
       'IsWicketDelivery', 'PlayerOut', 'Kind', 'FieldersInvolved',
       'BattingTeam'],
      dtype='object')